// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.15.0 DO NOT EDIT.
package oapi

import (
	user "github.com/vasiliiperfilev/ddd/internal/users/domain/user"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// User defines model for User.
type User = user.ResponseDto
