openapi: "3.0.0"
info:
  version: 1.0.0
  title: Wild Workouts users
  description: TODO
  contact:
    name: Vasilii Perfilev
    url: https://github.com/vasiliiperfilev
servers:
  - url: https://{hostname}/api
    variables:
      hostname:
        default: localhost
security:
  - bearerAuth: []
paths:

  /users/current:
    get:
      operationId: getCurrentUser
      responses:
        '200':
          description: todo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    User:
      type: object
      required:
        - id
        - displayName
        - balance
        - role
      properties:
        id:
          type: string
        displayName:
          type: string
        balance:
          type: integer
        role:
          type: integer
          x-go-type: auth.Role
          x-go-type-import:
            name: auth
            path: github.com/vasiliiperfilev/ddd/internal/common/auth
      x-go-type: user.ResponseDto
      x-go-type-import:
        name: user
        path: github.com/vasiliiperfilev/ddd/internal/users/domain/user

    Error:
      type: object
      required:
        - slug
        - message
      properties:
        slug:
          type: string
        message:
          type: string
