// Package main provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.15.0 DO NOT EDIT.
package main

import (
	auth "github.com/vasiliiperfilev/ddd/internal/common/auth"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// User defines model for User.
type User struct {
	Balance     int       `json:"balance"`
	DisplayName string    `json:"displayName"`
	Role        auth.Role `json:"role"`
}
